[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aqa-platform"
version = "0.1.0"
description = "Automated Quality Assurance Platform"
readme = "README.md"
requires-python = ">=3.12"

authors = [
  {name = "Hamza Ghaffar"}
]

license = {text = "MIT"}

dependencies = [
    "pytest>=9.0",
    "pytest-html>=4.2.0",
    "pytest-order>=1.4.0",
    "playwright>=1.50.0"
]

[project.optional-dependencies]
dev = [
    "pytest-cov>=4.0",
    "black>=23.0",
    "ruff>=0.1.0",
    "mypy>=1.0"
]

[tool.uv]
managed = true
preview = false

[tool.hatch.build.targets.wheel]
packages = ["qa-framework"]